Repository somcomunitats-coop/odoo-ec, pull requests merged in 2025-09, with the labels that each got.

#627 [FIX] 🐛 licence must to be GNU AGPLv3.0 and fix main README
  LICENSE
  README.md
Labels: documentation

#619 [IMP] Invoice endpoint
  README.md
  energy_communities/README.md
  energy_communities_api/README.md
  energy_communities_api/__manifest__.py
  energy_communities_api/components/partner_api_info.py
  energy_communities_api/models/__init__.py
  energy_communities_api/models/account_move.py
  energy_communities_api/schemas/__init__.py
  energy_communities_api/schemas/community.py
  energy_communities_api/schemas/invoice.py
  energy_communities_api/services/member_api_service.py
  energy_communities_api/tests/components/test_member_api_info.py
  energy_communities_api/tests/test_member_api_service.py
  energy_communities_service_invoicing/README.md
  energy_communities_service_invoicing/__manifest__.py
  energy_communities_service_invoicing/config.py
  energy_communities_service_invoicing/models/account_move.py
  energy_communities_service_invoicing/tests/__init__.py
  energy_communities_service_invoicing/tests/test_account_move.py
  energy_communities_service_invoicing/utils.py
Labels: to be reviewed

#628 [IMP] ✨ Make CE assistants menu entry visible to all except ce_users
  energy_communities/config.py
  energy_communities/views/menus.xml
  energy_communities_service_invoicing/README.md
  energy_communities_service_invoicing/__manifest__.py
  energy_communities_service_invoicing/config.py
  energy_communities_service_invoicing/security/ir.model.access.csv
  energy_communities_service_invoicing/tests/__init__.py
  energy_communities_service_invoicing/tests/test_pack_product_creator_wizard.py
  energy_communities_service_invoicing/views/menus.xml
  energy_communities_service_invoicing/wizards/pack_product_creator.py
  energy_communities_service_invoicing/wizards/pack_product_creator.xml
Labels: to be merged

#630 bump energy_communities version
  energy_communities/README.md
  energy_communities/__manifest__.py
Labels: in prod
